spring.application.name=blogwebsite


spring.datasource.url=jdbc:postgresql://localhost:5432/thedispatch

spring.datasource.username= postgres
spring.datasource.password= aditya@9916A

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# CORS (adjust frontend origin if needed)
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000,http://localhost:8081/auth/signup,http://localhost:8081/auth/login,http://localhost:8081/auth/me

jwt.secret=  mySuperSecretKeyWhichIsAtLeast32CharsLong123!
jwt.expirationMs= 86400000

# Server
server.port=8082

